//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estabelecimento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estabelecimento()
        {
            this.EstabelecimentoAcessibilidade = new HashSet<EstabelecimentoAcessibilidade>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public Nullable<int> IDTelefone { get; set; }
        public Nullable<int> IDEndereco { get; set; }
        public Nullable<int> IDTipo { get; set; }
    
        public virtual Endereco Endereco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstabelecimentoAcessibilidade> EstabelecimentoAcessibilidade { get; set; }
        public virtual Telefone Telefone { get; set; }
        public virtual TipoEstabelecimento TipoEstabelecimento { get; set; }
    }
}
