//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstabelecimentoAcessibilidade
    {
        public int ID { get; set; }
        public Nullable<int> IDEstabelecimento { get; set; }
        public Nullable<int> IDAcessibilidade { get; set; }
    
        public virtual Acessibilidade Acessibilidade { get; set; }
        public virtual Estabelecimento Estabelecimento { get; set; }
    }
}
